### ISSUE TITLE
Whom to request supporting documents for visa application?

### ISSUE THREAD

**Issue by abrahamdsl** [perlconference/tprc-2023-tor#1]
My passport (Philippines) is being required to have a visa in order to enter Canada. I would like to ask if someone , a main organizer could provide an invitation or similar document to be submitted to our Canadian Embassy E (or USAmerica's  in connection with Canada's new policy https://www.cnnphilippines.com/news/2023/6/7/Canada-visa-travel-Philippines.html  ) here.

**Comment by toddr** [comment]
Sorry, this query was lost. Hope you made it!
