### ISSUE TITLE
Be effective with git title

### ISSUE THREAD

**Issue by toddr** [perlconference/tprc-2023-tor#13]
Hello. Could somebody please fix my name at title for "Be effective with git" talk? I am "Eugen Konkov" not "Eugen Narkov". Also I published .gitconfig and other use full aliases on http://github.com/KES777/speedup_git. Please add this link into description for the video. So people could configure the same. Thank you

**Comment by toddr** [comment]
https://www.youtube.com/watch?v=4hTq-Gsue3A

**Comment by jeturcotte** [comment]
Hmm; no idea where 'Nar' could have come from, but alas he had no title and didn't say, so wherever it found its way into my head, I didn't have anything to contradict it either.  =(

Is replaced; only took a few minutes to do, but alas all the views...

If there's a signup form for lightning talks, can we get a description field on it?  No one's coming around to give any, so they're all quite blank.

**Comment by EugenKon** [comment]
Thank you guys.
