### ISSUE TITLE
State of Raku talk is too long. 

### ISSUE THREAD

**Issue by toddr** [perlconference/tprc-2023-tor#3]
should be 5 minutes not 50

https://youtu.be/TbYPZx4KHFE

**Comment by jeturcotte** [comment]
yep, found a distant fragment of the original camera file waaaaay out at the end outside of the visible timeline... THANKFULLY, this one can be tweaked by the in-youtube editor without me having to wreck the file's stats... (in process, may take YT a lil bit to finalize, internally) ... put it live once you've seen that it looks right

**Comment by toddr** [comment]
It's already live?

**Comment by jeturcotte** [comment]
i think so; I looked at it and saw no obvious issues
