### ISSUE TITLE
Regex - Is it so Simple? wrong speaker

### ISSUE THREAD

**Issue by toddr** [perlconference/tprc-2023-tor#5]
https://www.youtube.com/watch?v=G7Sa_Q0XG1A

"Regex - Is it so Simple? - Sawyer X"

Should be 

"Regex - Is it so Simple? - Matthew Stuckwisch"

**Comment by saiftynet** [comment]
Have to admit they look similar...DNA test required to verify?

**Comment by jeturcotte** [comment]
heheh

**Comment by jeturcotte** [comment]
I just don't know either of them well, and i was in a mad rush with the final batch

**Comment by jeturcotte** [comment]
https://youtu.be/IrtNmpOg-B0 ... put it live when you are confident

**Comment by toddr** [comment]
LGTM. it's live. Thank you!

**Comment by alabamenhu** [comment]
> Have to admit they look similar...DNA test required to verify?

I will take this as a massive complement that anyone confused me for @xsawyerx .
