### ISSUE TITLE
Add Mohammad to opening talk

### ISSUE THREAD

**Issue by toddr** [perlconference/tprc-2023-tor#6]
Could we add Mohammad's talk to the opening?

**Comment by jeturcotte** [comment]
we can't add it... we can only replace the entire opening with him added, which eliminates all the shared links and stats associated with the opening.  So it's a judgement call... separate video with just his acceptance (from day 3?) that's then added as a link at the end of the video (watch next), or replace everything?

**Comment by toddr** [comment]
I agree link in description?

**Comment by jeturcotte** [comment]
Yeah, if it's a separate video, i can link to it AND have a 'watched next' at the end

**Comment by jeturcotte** [comment]
On the one it's frustrating that I can't replace the underlying video (like I can the thumbnail or description) but then I also see lots of abuse if they did allow it.

**Comment by jeturcotte** [comment]
see: https://youtu.be/PMGKwuTiEJk

**Comment by jeturcotte** [comment]
see the end of https://www.youtube.com/watch?v=F36Tdrcg1tI

**Comment by toddr** [comment]
there's now a card on the end of the opening pointing to mohammad's thankyou. perfect thank you!
